apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bird-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: bird.local
      http:
        paths:
          - path: /ums(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: ums-service
                port:
                  number: 9000
          - path: /twitter(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: twitter-service
                port:
                  number: 9001
          - path: /()(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: ui-service
                port:
                  number: 80